import { generateUniqueId } from "Editors/generate_id";
import { ElementOptions } from "types";

export const defaultValuesElement: ElementOptions = {
  id: generateUniqueId("U2FsdGVkX18n4d9fnfqYO3VfsBk+Xw7Co68qvZcD/KzC3uvtCMpY9Hsx4Q3nxLDh5CTQFuAvDpmZc+yg3akk0g=="),
  name: "element",
  type: "cube",
  color: "#00FF00",
  opacity: "1",
  enablecenter: false,
  position_mode: "manual",
  position_reference_target_id: "",
  position_offsetx: "0",
  position_offsety: "0",
  position_offsetz: "0",
  elementaxisx: "0",
  elementaxisy: "0",
  elementaxisz: "0",
  rotationx: "0",
  rotationy: "0",
  rotationz: "0",
  elementsizeX: "1",
  elementsizeY: "1",
  elementsizeZ: "1",
  radiuis: "1",
  segmentswidth: "32",
  segmentsheight: "16",
  elementurl: "https://example.com/model.glb",
  traverse: false,
  subelements: [],
  points: [
    { x: "0", y: "1" },
    { x: "1", y: "0" },
    { x: "0", y: "-1" },
    { x: "-1", y: "0" },
  ],
  points3d: [
    { x: "0", y: "0", z: "0" },
    { x: "1", y: "0", z: "0" },
  ],
  line3d_radius: "0.1",
  line3d_radius_query: "static",
  line3d_tube_segments: "64",
  line3d_radial_segments: "8",
  line3d_closed: false,
  line3d_smooth: false,
  line3d_set_points_manually: true,
  hover: true,
  hovercolor: "#00FF00",
  helpwindow: false,
  make_clikable: false,
  open_in_current: false,
  link: "https://google.com",
  double_side: false,
  addText: false,
  textsettings: { text: "Enter text", useGlobalTextSettings: true },
  font: "Arial",
  fontsize: "1",
  font_aligh: "center",
  smooth: "0",
  lineHeight: "1",
  letterSpacing: "1",
  text_of_element_width: "10",
  bordersforelement: false,
  bordersforelementwidth: "1",
  bordersforelementcolor: "#ffffff",
  usegradient: false,
  gradientcolor: {
    lowvalueforgradient: "0",
    highvalueforgradient: "100",
    gradientsaturation: "100",
    gradinetlightnes: "50",
    lowvaluegradientcolor: { h: 100, s: 100, l: 50 },
    highvaluegradientcolor: { h: 200, s: 100, l: 50 },
  },
  enablecolorquery: false,
  colorquery: "",
  value: "0",
  center: { x: "0", y: "0" },
  center_grid_color: "#ff0000",
  extrudex: false,
  extrudey: true,
  extrudez: false,
  keybind: "l",
  bevel: { bevelEnabled: true, steps: "1", bevelThickness: "0", bevelSize: "0", beveloffset: "0", bevelSegments: "0" },
};
